# -*- coding: utf-8 -*-
"""credit

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1xgXKs-aYvunum_Xr4Yg4AncXISf4X2j0
"""

# ler do usuario o numero do cartão
print("Não colocar espaços") 
numero_cartao_possivel_erro = list(input())
# Iniciar uma lista vazia para ser usada depois
numero_cartao = []
# deletar qualquer coisa que já tiver salvo na lista numero_cartao
del numero_cartao[:]

# Tratamento de erro: remove qualquer caracter não numerico
for item in numero_cartao_possivel_erro:
  if (item.isdigit()): # apenas caracteres numericos são adicionados
    numero_cartao.append(item)

# Transforma a lista, até então de strings, em uma lista de inteiros
lista_inteiros = list(map(int, numero_cartao))
lista_dobrados = []
# Le a lista de inteiros de tras para frente, começando do pnultimo e lendo um sim um não
for item in list(reversed(lista_inteiros))[1::2]:
    x = item * 2
    lista_dobrados.append(x)

# Para numero maiores que 9, subtrair nove (assim gerando o resultado da soma dos digitos. Exemplo: 10 - 9 = 1 and 1 + 0 = 1)
# Para numeros menores que 9, apenas adicionar à nova lista
lista_somatoria = []
for item in lista_dobrados:
  if item > 9:
    lista_somatoria.append(item - 9)
  else:
    lista_somatoria.append(item)

# Pega todos os numeros que sobraram da lista original e adiciona eles na lista_somatoria para participarem da somatoria
for item in list(reversed(lista_inteiros))[::2]:
  lista_somatoria.append(item)

# Primeiro é verificado se a somatoria é multipla de 10, caso não seja o processo encerra sem precisar verificar a bandeira
# Caso a primeira verificação passe, é então verificado qual a bandeira do cartão (VISA, MASTERCARD ou AMEX) e retoramos o valor apropriado
if sum(lista_somatoria) % 10 == 0:
  if lista_inteiros[0] == 4:
    print("VISA")
  elif lista_inteiros[0] == 5 and (lista_inteiros[1] == 1 or 2 or 3 or 4 or 5):
    print("MASTERCARD")
  elif lista_inteiros[0] == 3 and (lista_inteiros[1] == 4 or 7):
    print("AMEX")
  else:
    print("Invalido")
else:
    print("Invalido")